In [1]:
import tensorflow as tf

############
# Use Matrix
############
x_data = [[73., 80., 75.], [93.,88.,93.],
           [89., 91.,90.], [96., 98.,100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

############
# Use Matrix
############

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction: \n", hy_val)

0 Cost: 33985.812 
Prediction: 
 [[-20.04289  ]
 [ -6.3664074]
 [-15.5802355]
 [-16.390415 ]
 [ -0.6460364]]
10 Cost: 31.767878 
Prediction: 
 [[142.98422]
 [189.5388 ]
 [177.46997]
 [193.83392]
 [148.77211]]
20 Cost: 31.2878 
Prediction: 
 [[143.4992 ]
 [190.1167 ]
 [178.06073]
 [194.4748 ]
 [149.20471]]
30 Cost: 31.119465 
Prediction: 
 [[143.5224 ]
 [190.10359]
 [178.06917]
 [194.48149]
 [149.18658]]
40 Cost: 30.951965 
Prediction: 
 [[143.54407]
 [190.08875]
 [178.0758 ]
 [194.48625]
 [149.16713]]
50 Cost: 30.785442 
Prediction: 
 [[143.56566]
 [190.07393]
 [178.08241]
 [194.491  ]
 [149.14774]]
60 Cost: 30.619888 
Prediction: 
 [[143.58719]
 [190.0592 ]
 [178.08902]
 [194.49576]
 [149.12839]]
70 Cost: 30.455103 
Prediction: 
 [[143.60867]
 [190.04445]
 [178.0956 ]
 [194.50046]
 [149.1091 ]]
80 Cost: 30.29127 
Prediction: 
 [[143.63011]
 [190.0298 ]
 [178.10219]
 [194.5052 ]
 [149.08987]]
90 Cost: 30.128265 
Prediction: 
 [[143.65149]
 [190.01515]
 [178.10873]
 [194.50992]
 [149.07

840 Cost: 20.112112 
Prediction: 
 [[145.09969]
 [189.02263]
 [178.5528 ]
 [194.8285 ]
 [147.77043]]
850 Cost: 20.004154 
Prediction: 
 [[145.11707]
 [189.0107 ]
 [178.55812]
 [194.83232]
 [147.7548 ]]
860 Cost: 19.896866 
Prediction: 
 [[145.1344 ]
 [188.99881]
 [178.56345]
 [194.83612]
 [147.73926]]
870 Cost: 19.79005 
Prediction: 
 [[145.1517 ]
 [188.98697]
 [178.56876]
 [194.83997]
 [147.72372]]
880 Cost: 19.683857 
Prediction: 
 [[145.16896]
 [188.97514]
 [178.57405]
 [194.84373]
 [147.70825]]
890 Cost: 19.578218 
Prediction: 
 [[145.18616]
 [188.96335]
 [178.57932]
 [194.8475 ]
 [147.6928 ]]
900 Cost: 19.473143 
Prediction: 
 [[145.20332]
 [188.9516 ]
 [178.5846 ]
 [194.85129]
 [147.6774 ]]
910 Cost: 19.368639 
Prediction: 
 [[145.22044]
 [188.93987]
 [178.58983]
 [194.85506]
 [147.66205]]
920 Cost: 19.264713 
Prediction: 
 [[145.2375 ]
 [188.92816]
 [178.59506]
 [194.8588 ]
 [147.64673]]
930 Cost: 19.161366 
Prediction: 
 [[145.25452]
 [188.9165 ]
 [178.60028]
 [194.86255]
 [147

1700 Cost: 12.67168 
Prediction: 
 [[146.4358 ]
 [188.10696]
 [178.96257]
 [195.12193]
 [146.5714 ]]
1710 Cost: 12.603922 
Prediction: 
 [[146.44957]
 [188.0975 ]
 [178.96678]
 [195.12494]
 [146.559  ]]
1720 Cost: 12.536589 
Prediction: 
 [[146.46332]
 [188.0881 ]
 [178.97101]
 [195.12794]
 [146.54669]]
1730 Cost: 12.469576 
Prediction: 
 [[146.47702]
 [188.0787 ]
 [178.9752 ]
 [195.13097]
 [146.5344 ]]
1740 Cost: 12.402952 
Prediction: 
 [[146.49069]
 [188.06935]
 [178.97942]
 [195.13396]
 [146.52214]]
1750 Cost: 12.336687 
Prediction: 
 [[146.50432]
 [188.06   ]
 [178.98358]
 [195.13695]
 [146.50992]]
1760 Cost: 12.270749 
Prediction: 
 [[146.51791]
 [188.05069]
 [178.98776]
 [195.13992]
 [146.49771]]
1770 Cost: 12.205162 
Prediction: 
 [[146.53148]
 [188.0414 ]
 [178.99193]
 [195.1429 ]
 [146.48555]]
1780 Cost: 12.139951 
Prediction: 
 [[146.545  ]
 [188.03212]
 [178.99605]
 [195.14586]
 [146.47342]]
1790 Cost: 12.075102 
Prediction: 
 [[146.55847]
 [188.02289]
 [179.00021]
 [195.14