In [19]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=0.0).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val,W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 1.6932343 [[-1.0597816   0.7818453   0.95948017]
 [ 0.9351161  -0.28904843  0.15402111]
 [-1.3577473  -0.77172637 -0.9627301 ]]
1 1.608928 [[-1.0624979   0.7850602   0.9589815 ]
 [ 0.9241435  -0.27303424  0.14897954]
 [-1.3661946  -0.75510424 -0.970905  ]]
2 1.5286193 [[-1.0651244   0.7881858   0.9584825 ]
 [ 0.91359556 -0.25731406  0.14380728]
 [-1.37422    -0.73888105 -0.97910273]]
3 1.4527586 [[-1.0676633   0.79120857  0.95799863]
 [ 0.9034644  -0.24194515  0.13856956]
 [-1.3818309  -0.7231236  -0.9872492 ]]
4 1.3818362 [[-1.0701147   0.79411435  0.95754427]
 [ 0.8937531  -0.22699322  0.13332893]
 [-1.3890238  -0.7079055  -0.9952744 ]]
5 1.3163471 [[-1.072477    0.7968881   0.9571328 ]
 [ 0.8844753  -0.21253175  0.12814529]
 [-1.395785   -0.69330573 -1.0031129 ]]
6 1.2567451 [[-1.0747471   0.7995147   0.9567763 ]
 [ 0.8756533  -0.19864027  0.12307581]
 [-1.4020927  -0.6794067  -1.0107042 ]]
7 1.2033923 [[-1.076921    0.8019795   0.9564854 ]
 [ 0.86731577 -0.18540117  0.11817428]
 

125 0.88030565 [[-1.1805825   0.80290455  1.0592215 ]
 [ 0.7116477  -0.0112888   0.09972987]
 [-1.308888   -0.6101359  -1.1731789 ]]
126 0.8797215 [[-1.1813344   0.8027369   1.0601411 ]
 [ 0.710869   -0.01077653  0.09999626]
 [-1.3077382  -0.6105658  -1.1738988 ]]
127 0.87913936 [[-1.1820855   0.80256945  1.0610597 ]
 [ 0.7100919  -0.01026518  0.10026202]
 [-1.3065904  -0.61099476 -1.1746175 ]]
128 0.8785589 [[-1.1828359   0.8024022   1.0619774 ]
 [ 0.7093163  -0.00975475  0.10052717]
 [-1.3054447  -0.61142284 -1.1753352 ]]
129 0.87797993 [[-1.1835856   0.8022351   1.0628942 ]
 [ 0.7085423  -0.00924525  0.10079169]
 [-1.304301   -0.61184996 -1.1760516 ]]
130 0.87740254 [[-1.1843346   0.80206823  1.0638101 ]
 [ 0.7077698  -0.00873668  0.1010556 ]
 [-1.3031594  -0.6122762  -1.176767  ]]
131 0.87682694 [[-1.1850829   0.8019015   1.064725  ]
 [ 0.7069989  -0.00822903  0.10131889]
 [-1.3020197  -0.61270154 -1.1774813 ]]
132 0.8762529 [[-1.1858305   0.801735    1.065639  ]
 [ 0.7062295  -0.0

191 0.8450868 [[-1.2287263   0.79225713  1.1180131 ]
 [ 0.66352063  0.02055093  0.11601739]
 [-1.2372564  -0.63659775 -1.2183477 ]]
192 0.84460163 [[-1.2294343   0.7921026   1.1188756 ]
 [ 0.66284144  0.02100291  0.11624462]
 [-1.2362356  -0.6369695  -1.2189966 ]]
193 0.8441177 [[-1.2301416   0.79194826  1.1197373 ]
 [ 0.6621637   0.021454    0.11647129]
 [-1.2352167  -0.6373404  -1.2196447 ]]
194 0.8436351 [[-1.2308484   0.7917941   1.1205981 ]
 [ 0.6614874   0.02190418  0.1166974 ]
 [-1.2341998  -0.6377105  -1.2202916 ]]
195 0.8431536 [[-1.2315546   0.7916402   1.1214582 ]
 [ 0.66081256  0.02235347  0.11692294]
 [-1.2331846  -0.6380797  -1.2209376 ]]
196 0.8426738 [[-1.2322602   0.79148656  1.1223174 ]
 [ 0.6601392   0.02280187  0.11714793]
 [-1.2321713  -0.63844806 -1.2215825 ]]
197 0.8421951 [[-1.2329652   0.7913331   1.1231759 ]
 [ 0.6594673   0.02324937  0.11737236]
 [-1.2311598  -0.6388156  -1.2222265 ]]
198 0.8417177 [[-1.2336696   0.79117984  1.1240336 ]
 [ 0.6587968   0.02369