In [2]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b 

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction: \n", hy_val)

0 Cost: 224364.28 
Prediction: 
 [-269.157   -320.90433 -318.0272  -339.96588 -249.43126]
10 Cost: 17.153545 
Prediction: 
 [149.83966 182.7107  178.18707 200.39798 134.70406]
20 Cost: 15.075907 
Prediction: 
 [151.10101 184.239   179.68669 202.03008 135.87364]
30 Cost: 15.052063 
Prediction: 
 [151.0985  184.24815 179.6895  202.03212 135.88449]
40 Cost: 15.028506 
Prediction: 
 [151.09213 184.2527  179.68774 202.02928 135.8918 ]
50 Cost: 15.004941 
Prediction: 
 [151.08582 184.25723 179.68605 202.02643 135.89911]
60 Cost: 14.981501 
Prediction: 
 [151.07947 184.2617  179.68431 202.02354 135.90637]
70 Cost: 14.958181 
Prediction: 
 [151.07314 184.26617 179.68256 202.02066 135.9136 ]
80 Cost: 14.934919 
Prediction: 
 [151.06686 184.27065 179.68085 202.01779 135.92084]
90 Cost: 14.91181 
Prediction: 
 [151.0606  184.27513 179.67915 202.01495 135.92805]
100 Cost: 14.888672 
Prediction: 
 [151.05435 184.27959 179.67746 202.01208 135.93527]
110 Cost: 14.865727 
Prediction: 
 [151.04814 184.

1010 Cost: 13.13999 
Prediction: 
 [150.55815 184.6345  179.54417 201.76999 136.52397]
1020 Cost: 13.124069 
Prediction: 
 [150.5534  184.6379  179.54292 201.76752 136.52977]
1030 Cost: 13.10815 
Prediction: 
 [150.5487  184.64125 179.54169 201.76501 136.53554]
1040 Cost: 13.092366 
Prediction: 
 [150.544   184.64462 179.54044 201.76256 136.5413 ]
1050 Cost: 13.076599 
Prediction: 
 [150.53932 184.648   179.5392  201.76009 136.54706]
1060 Cost: 13.060869 
Prediction: 
 [150.53467 184.65137 179.538   201.75761 136.5528 ]
1070 Cost: 13.045169 
Prediction: 
 [150.53003 184.65472 179.53677 201.75516 136.55855]
1080 Cost: 13.029553 
Prediction: 
 [150.5254  184.65808 179.53557 201.7527  136.56427]
1090 Cost: 13.014048 
Prediction: 
 [150.52077 184.6614  179.53435 201.75024 136.56996]
1100 Cost: 12.998548 
Prediction: 
 [150.51616 184.66472 179.53316 201.74779 136.57565]
1110 Cost: 12.9831295 
Prediction: 
 [150.51154 184.668   179.53192 201.7453  136.5813 ]
1120 Cost: 12.9678135 
Prediction

2000 Cost: 11.808413 
Prediction: 
 [150.1554  184.92621 179.4407  201.54028 137.03749]
