In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(7777)

############
# Load Data
############
xy = np.loadtxt('LoadData.csv', delimiter=',', dtype=np.float32)

# 불러온 데이터 행렬에서 모든 행에서 마지막열을 제외한 모든 데이터값저장
x_data = xy[:, 0:-1]
# 불러온 데이터 행렬에서 모든 행에서 마지막열의 데이터 값만 저장.
y_data = xy[:, [-1]]
# 잘가져왔나 확인
print("x_data.shape: ", x_data.shape, "\n x_data: ", x_data, "\n len(x_data):", len(x_data))
print("y_data.shape: ", y_data.shape, "\n y_data: ,", y_data)

X = tf.placeholder(tf.float32, shape=[None, 3]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

############
# Load Data
############

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction: \n", hy_val)
        

###############
#Ask for Score
###############
print("My Score :", sess.run(hypothesis,
                            feed_dict={X: [[100, 70, 101]]}))

x_data.shape:  (6, 3) 
 x_data:  [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 
 len(x_data): 6
y_data.shape:  (6, 1) 
 y_data: , [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost: 10621.541 
Prediction: 
 [[56.447517]
 [66.597786]
 [66.27766 ]
 [73.58793 ]
 [49.031807]
 [37.60194 ]]
10 Cost: 6.183727 
Prediction: 
 [[152.49796 ]
 [182.08493 ]
 [180.0472  ]
 [197.48534 ]
 [137.12552 ]
 [102.545235]]
20 Cost: 5.686951 
Prediction: 
 [[153.14377]
 [182.86969]
 [180.81606]
 [198.32217]
 [137.72655]
 [102.98858]]
30 Cost: 5.6770597 
Prediction: 
 [[153.14345]
 [182.87761]
 [180.8196 ]
 [198.32558]
 [137.73503]
 [102.99508]]
40 Cost: 5.667269 
Prediction: 
 [[153.13878]
 [182.88026]
 [180.81801]
 [198.32338]
 [137.7395 ]
 [102.99861]]
50 Cost: 5.6575303 
Prediction: 
 [[153.13408]
 [182.88284]
 [180.81635]
 [198.3211 ]
 [137.74391]
 [103.00211]]
60 Cost: 5.647833 
Prediction: 
 [[153.12943]
 [182.88547]
 [180.81473]
 [198.

730 Cost: 5.087421 
Prediction: 
 [[152.84991]
 [183.04259]
 [180.71841]
 [198.17784]
 [138.02055]
 [103.20808]]
740 Cost: 5.0802355 
Prediction: 
 [[152.8462 ]
 [183.04468]
 [180.71715]
 [198.17586]
 [138.02428]
 [103.21066]]
750 Cost: 5.07307 
Prediction: 
 [[152.84251]
 [183.0468 ]
 [180.71593]
 [198.17393]
 [138.02803]
 [103.21326]]
760 Cost: 5.0659146 
Prediction: 
 [[152.83882]
 [183.0489 ]
 [180.71468]
 [198.17195]
 [138.03174]
 [103.21582]]
770 Cost: 5.058815 
Prediction: 
 [[152.83516]
 [183.051  ]
 [180.71342]
 [198.17   ]
 [138.03545]
 [103.21838]]
780 Cost: 5.0517173 
Prediction: 
 [[152.8315 ]
 [183.05309]
 [180.7122 ]
 [198.16806]
 [138.03917]
 [103.22093]]
790 Cost: 5.044671 
Prediction: 
 [[152.82785 ]
 [183.05516 ]
 [180.71097 ]
 [198.16609 ]
 [138.04285 ]
 [103.223465]]
800 Cost: 5.0376472 
Prediction: 
 [[152.82423]
 [183.05724]
 [180.70976]
 [198.16417]
 [138.04655]
 [103.226  ]]
810 Cost: 5.0306373 
Prediction: 
 [[152.8206  ]
 [183.05931 ]
 [180.70854 ]
 [198.1622

1460 Cost: 4.629189 
Prediction: 
 [[152.61005]
 [183.18152]
 [180.6391 ]
 [198.04361]
 [138.27216]
 [103.36949]]
1470 Cost: 4.6236978 
Prediction: 
 [[152.60715]
 [183.18323]
 [180.63817]
 [198.04189]
 [138.27533]
 [103.37132]]
1480 Cost: 4.6182647 
Prediction: 
 [[152.60428]
 [183.18494]
 [180.63725]
 [198.04019]
 [138.2785 ]
 [103.37318]]
1490 Cost: 4.612862 
Prediction: 
 [[152.60141]
 [183.18663]
 [180.63635]
 [198.03848]
 [138.28165]
 [103.37501]]
1500 Cost: 4.607468 
Prediction: 
 [[152.59856]
 [183.18831]
 [180.6354 ]
 [198.03676]
 [138.28477]
 [103.37682]]
1510 Cost: 4.602082 
Prediction: 
 [[152.59572]
 [183.18999]
 [180.6345 ]
 [198.03505]
 [138.28792]
 [103.37863]]
1520 Cost: 4.5966945 
Prediction: 
 [[152.59288]
 [183.1917 ]
 [180.6336 ]
 [198.03337]
 [138.29108]
 [103.38045]]
1530 Cost: 4.591327 
Prediction: 
 [[152.59004 ]
 [183.19336 ]
 [180.63269 ]
 [198.03166 ]
 [138.2942  ]
 [103.382225]]
1540 Cost: 4.5860143 
Prediction: 
 [[152.58722]
 [183.195  ]
 [180.63177]
 [19