# Tensor Manipulation

In [ ]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## Simple Array

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [6]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [7]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [5]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

## Axis의 의미는 축(시작점)을 의미한다.
## Rank를 나타내는 [[[...]]]중 가장 바깥쪽의 []를 Axis=0이라고 나타내고
## 안쪽으로 갈 수록 숫자가 증가한다. 또한 slicing과 같이 가장 마지막 즉 []의 가장 안쪽을 Axis=-1로 나타난다

array([1, 2, 3, 4])

## Matmul VS multiply

In [8]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
#행렬곱
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [9]:
#일반곱하기 행렬곱이아님
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

## Watch out broadcasting

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()
#형태가 달라도 똑같이 형태를 똑같이 만들어주고 연산을 한다.
#broadcasting을 사용할때는 행렬의 형태를 똑같이 만들어서 연산해주는게 좋다.

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

## Reduce Mean/Sum

In [12]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [13]:
 x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

2.5

In [14]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [15]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [16]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [17]:
tf.reduce_sum(x).eval()

10.0

In [18]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [19]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [20]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [21]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [22]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [23]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape, squeeze(압착), expand_dims

In [24]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [26]:
tf.reshape(t, shape=[-1, 3]).eval()
##reshape을 하면 Rank가 한 차수 줄어듦

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [28]:
tf.squeeze([[0], [1], [2]]).eval()
## Rank를 줄이는 것!

array([0, 1, 2])

In [29]:
tf.expand_dims([0, 1, 2], 1).eval()
## Rank를 늘리는 것! ([],숫자) 숫자 => 몇개나 늘릴것인가?

array([[0],
       [1],
       [2]])

## One hot

In [30]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
## one_hot은 Rank를 하나 증가시킨다.

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [31]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()
## Rank를 증가시키는것이 싫다면 reshape을 사용한다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## casting

In [32]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [33]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [34]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [40]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()
#행렬 x와 같은 모양을 가지는 1로 채워진 행렬생성

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
tf.zeros_like(x).eval()
#행렬 x와 같은 모양을 가지는 0으로 채워진 행렬 생성

array([[0, 0, 0],
       [0, 0, 0]])

## Zip


In [42]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [43]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [48]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [44]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(1, 4, 3)
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]], dtype=float32)


In [45]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(4, 1, 3)
array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)


In [46]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(1, 3, 4)
array([[[1., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)


In [47]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(4, 1, 3)
array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)
